[package]
name = "text-adventure-01"
version = "0.1.0"
authors = ["Alexei Ozerov <ozerovmusic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
text_io = "0.1.8"
ferris-says = "0.2"
